/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}

dependencies {

}

javafx {
    version = "21"
    modules = listOf("javafx.controls", "javafx.fxml")
}

application {
    mainClass.set("it.unicam.cs.mpgc.jbudget125637.Main")

}

tasks.named<JavaExec>("run") {
    jvmArgs = listOf("--module-path", "path/to/javafx-sdk/lib", "--add-modules", "javafx.controls,javafx.fxml")
    // Disattiva configuration cache per il task run
    notCompatibleWithConfigurationCache("JavaFX run task not supported with configuration cache")
}

